"""Add image column to restaurants

Revision ID: 9bcc06270d2c
Revises: 72d9d4dd84ce
Create Date: 2025-04-13 01:59:31.157585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcc06270d2c'
down_revision = '72d9d4dd84ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
